In [1]:
import numpy as np

In [2]:
import primePkg as pp

In [3]:
pp.isPrime(886127)

0

In [4]:
pset=np.array(list(pp.primeSet)).reshape(267,294)

AttributeError: module 'primePkg' has no attribute 'primeSet'

In [ ]:
n=78498
l=list()
r=int(n**.5)
i=1
if(r**2==n):
    l.append(r)
while(i<r):
    if(n%i==0):
        l.append(int(i))        
        l.append(int(n/i))
        print("i = ",i," n = ",n/i)
    i=i+1
print(l)

In [6]:
import pandas as pd

In [ ]:
df=pd.DataFrame(pset,np.arange(1,268),np.arange(1,295))

In [ ]:
df.head()

In [ ]:
type(df)

In [ ]:
a=np.array(df.values)

In [ ]:
b=a.flatten()

In [ ]:
b

In [ ]:
len(b)

In [ ]:
263843 in df.values

In [ ]:
df.head()

In [ ]:
len(pp.primeSet)

In [ ]:
df.to_csv("My_prime_dataset",index=False)

In [9]:
df2=pd.read_excel("My_prime_dataset.xlsx")

In [10]:
df2.head

<bound method NDFrame.head of         1       2       3       4       5       6       7       8       9    \
1    786433       2       3  262147       5       7  262151  262153  917513   
2    393629  524701  131489     419  524707     421  393637  262567  917923   
3       853  131927  525143     857  394073     859  787289  131933  656221   
4    918787    1289  132361    1291  394507  263437  656651  132367  525583   
5      1699  263843  657061  263849    1709  657071  394931  263863  657079   
6    133201    2131  657491  657493  788561  526423  788563    2137  657497   
7    264739  133669  789029  264743  657959  133673  789031  920107  264749   
8    658379    3023  396239  265169  396247  658391  920539    3037  527327   
9    265619  265621  658837  658841  396703    3491  396709  920999  396713   
10   266083  528223  659299  790369    3943  135017  266089    3947  135019   
11   659741  921887  528673  790817  790819  921889  135461    4391  135463   
12   791251  135893  6

In [12]:
df2.values

array([[786433,      2,      3, ..., 131479,    409, 262553],
       [393629, 524701, 131489, ..., 394063, 525137, 918353],
       [   853, 131927, 525143, ..., 525571, 263429, 394501],
       ...,
       [522689, 653761, 391619, ..., 261061, 785347, 523207],
       [785353, 523213, 785357, ..., 261593, 130523, 392669],
       [523741, 261601, 654817, ..., 262139, 655357, 131071]], dtype=int64)

In [ ]:
df.to_excel('My_prime_dataset.xlsx',sheet_name='NewSheet')

In [ ]:
df2=pd.read_excel('My_prime_dataset.xlsx')

In [15]:
4817 in df2.values

True

In [17]:
a=np.array(df2.values)

In [18]:
b=a.flatten()

In [19]:
b

array([786433,      2,      3, ..., 262139, 655357, 131071], dtype=int64)

In [30]:
b[(b<10000) & (b>1000)]

array([1009, 1013, 1019, ..., 9949, 9967, 9973], dtype=int64)